name: Builds
on:
  push:

defaults:
  run:
    # reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
    shell: bash --noprofile --norc -eo pipefail -x {0}

jobs:
  debug:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.pull_request.labels.*.name, 'skip-ci')"
    steps:
      - name: die
        run: |
          false

      - name: consider debugging
        if: failure()
        run: |
          if [ "$GITHUB_REPOSITORY_OWNER" = "rook" ] || [ -n "${{ secrets.USE_WEBSHELL }}" ] || [ "$GITHUB_RUN_ATTEMPT" -gt 1 ]; then
            echo USE_TMATE=1 >> $GITHUB_ENV
          fi

      - name: set up tmate session for debugging
        if: failure() && env.USE_TMATE
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 60
